/*
 * Copyright (c) 2021, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */
//-*- coding: utf-8 -*-
plugins {
  id 'ear'
}

dependencies {
  deploy project( path: ':casual:casual-caller')
  deploy project( path: ':casual:casual-caller-administration', configuration:'archives')
  earlib project( path: ':casual:casual-caller-api')
  earlib project( path: ':casual:casual-caller-http-client')
  earlib libs.casual_api_spi_impl
}

ear{
  deploymentDescriptor{
    applicationName = "casual-caller-administration-app"
    displayName = "Casual Caller Administration App"
    description = "Casual application that provides an abstraction layer on top of n # of CasualConnectionFactories"
  }
  manifest{
        attributes 'Dependencies' : 'jdk.unsupported'
  }
}

publishing {
  publications {
    mavenJava( MavenPublication ) {
      artifact ear
    }
  }
}
